### ISSUE TITLE
Tests coverage

### ISSUE THREAD

**Issue by pazairfog** [OWS/composer-dependencies-security-checker#1]
Creating this issue as a reminder to improve our tests coverage and allow external inputs to do so.

- [x] Use an old and vulnerable version
- [x] Use a newer and safe version
- [x] Use latest version but with a vulnerable dependencies

**Comment by jcisio** [comment]
Do you still need this reminder? ;-) With https://github.com/OWS/composer-dependencies-security-checker/pull/3 we both use old and new advisories so I think we kind of use real world data.
